public class CommonDto {
    
    
    
    
   /* public String imageURL {get;set;}
    public String userName {get;set;}
    public String success {get;set;}
    public String message {get;set;}
    public List<String> channelimage{set;get;}
    public List<String> channelName{set;get;}
    public void getSuccess(){
        imageURL= ApexPages.CurrentPage().getparameters().get('imageURL');
        userName= ApexPages.CurrentPage().getparameters().get('userName');
        success= ApexPages.CurrentPage().getparameters().get('success');
        message= ApexPages.CurrentPage().getparameters().get('message');
    }*/
}