public class Message {
    public String errorTag{set;get;}
    public String msg{set;get;}
    public String total_count{set;get;}
    public List<Peers> peers{set;get;}
    public List<Groups> groups{set;get;}
    public List<Categories> categories{set;get;}
    public List<Tours> tours{set;get;}
    public List<Steps> steps{set;get;}
    public PromotionInfo promotion_info{set;get;}
    public List<Speech> speech{set;get;}
    public List<Ratings> ratings{set;get;}
    public List<Mentors> mentors{set;get;}
}