public class SearchObject {
     public String speech_id{set;get;}
     public String video_id{set;get;}
    
    public void setSpeech_Id(String speech_id){
       speech_id = speech_id;
    }
    public String getSpeech_Id(){
      return speech_id;
    } 
     public void setVideo_id(String video_id){
       video_id = video_id;
    }
    public String getVideo_id(){
       return video_id;
    } 
}