public class UserDto {
    public String Id {set;get;}
    public String EmailId {get;set;}
    public String FirstName {set;get;}
    public String LastName {get;set;}
    public String Organization {set;get;}
    public String RegionId {get;set;}
    public String UserKey {set;get;}
    public String Region {get;set;}
    public String RoleId {get;set;}
    public String Role {get;set;}
    public String PhotoLink {get;set;}
}