public class Video {
    public String videotypeid{set;get;}
    public String taskid{set;get;}
    public String videotype{set;get;}
    public String elementtitle{set;get;}
    public String videoid{set;get;}
    public String hdvideo{set;get;}
    public String sdvideo{set;get;}
    public String taskimage{set;get;}
    public String containerid{set;get;}
    public String ismandatory{set;get;}
    public LONG uniquevideoid{set;get;}
    
    public String getTaskId(){
        return taskid;
    }
    public String getIsmandatory(){
        return ismandatory;
    }
}